import { NextApiRequest, NextApiResponse } from 'next'
import { jsPDF } from 'jspdf'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    const { report } = req.body

    if (!report) {
      return res.status(400).json({ error: 'Report data is required' })
    }

    console.log('📄 Generating PDF report for:', report.name)

    // Create PDF
    const doc = new jsPDF()
    
    // Add title
    doc.setFontSize(20)
    doc.text('ReportSonic AI Analysis Report', 20, 30)
    
    // Add report name
    doc.setFontSize(16)
    doc.text(`File: ${report.name}`, 20, 50)
    
    // Add creation date
    doc.setFontSize(12)
    doc.text(`Generated: ${new Date(report.createdAt).toLocaleString()}`, 20, 65)
    
    // Add summary
    doc.setFontSize(14)
    doc.text('Executive Summary', 20, 85)
    doc.setFontSize(10)
    const summaryLines = doc.splitTextToSize(report.analysis.summary, 170)
    doc.text(summaryLines, 20, 100)
    
    // Add insights
    let yPosition = 130
    doc.setFontSize(14)
    doc.text('Key Insights', 20, yPosition)
    yPosition += 10
    
    doc.setFontSize(10)
    report.analysis.insights.forEach((insight: string) => {
      doc.text(`• ${insight}`, 20, yPosition)
      yPosition += 7
    })
    
    // Add recommendations
    yPosition += 10
    doc.setFontSize(14)
    doc.text('Recommendations', 20, yPosition)
    yPosition += 10
    
    doc.setFontSize(10)
    report.analysis.recommendations.forEach((rec: string) => {
      doc.text(`• ${rec}`, 20, yPosition)
      yPosition += 7
    })
    
    // Add statistics table
    if (report.analysis.statistics && report.analysis.statistics.length > 0) {
      yPosition += 10
      doc.setFontSize(14)
      doc.text('Statistical Analysis', 20, yPosition)
      yPosition += 10
      
      doc.setFontSize(8)
      doc.text('Column', 20, yPosition)
      doc.text('Count', 60, yPosition)
      doc.text('Average', 90, yPosition)
      doc.text('Max', 120, yPosition)
      doc.text('Min', 150, yPosition)
      yPosition += 5
      
      report.analysis.statistics.forEach((stat: any) => {
        doc.text(stat.column, 20, yPosition)
        doc.text(stat.count.toString(), 60, yPosition)
        doc.text(stat.average.toFixed(2), 90, yPosition)
        doc.text(stat.max.toString(), 120, yPosition)
        doc.text(stat.min.toString(), 150, yPosition)
        yPosition += 5
      })
    }
    
    // Add footer
    doc.setFontSize(8)
    doc.text('Generated by ReportSonic AI', 20, doc.internal.pageSize.height - 20)

    // Generate PDF buffer
    const pdfBuffer = doc.output('arraybuffer')

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="${report.name.replace(/\.[^/.]+$/, '')}_report.pdf"`)
    res.setHeader('Content-Length', pdfBuffer.byteLength)

    // Send PDF
    res.status(200).send(Buffer.from(pdfBuffer))

  } catch (error: any) {
    console.error('❌ Export error:', error)
    return res.status(500).json({ 
      error: 'Failed to generate PDF report' 
    })
  }
}
